import Head from "next/head";

type Props = {
  title?: string;
  description: string;
  url: string;
  image?: string;
  // #todo: there can be more types of og:type
  type?: "article" | "website";
};

const Meta = ({
  title = "Formsly",
  description,
  url, // url should be a canonical url e.g https://www.imdb.com/title/tt0117500/
  // #todo: replace default image with brand image
  image = "/icon.svg", // Use custom images for “shareable” pages (e.g., homepage, articles, etc.)
  type = "website",
}: Props) => {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content={description} />
      <meta property="og:title" content={title} />
      <meta property="og:description" content={description} />
      {/* #todo: create an implementation where the canonical url is generated by default */}
      <meta property="og:url" content={url} />
      <meta property="og:image" content={image} />
      <meta property="og:type" content={type} />
      <link rel="icon" href={image} />
    </Head>
  );
};

export default Meta;
